apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: anything-llm
  name: anything-llm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: anything-llm
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/anythingllm-anything-llm: "true"
        io.kompose.service: anything-llm
    spec:
      initContainers:
        - name: init-chmod-data
          image: >-
            mintplexlabs/anythingllm:master
          command:
            - /bin/bash
            - '-cxe'
            - |
                chown -R 1000:1000 /app/server/storage
                chown -R 1000:1000 /app/collector/hotdir
                chown -R 1000:1000 /app/collector/outputs
                chmod -R 700 /app/server/storage
                chmod -R 700 /app/collector/hotdir
                chmod -R 700 /app/collector/outputs
          volumeMounts:
            - mountPath: /app/server/storage
              name: server-storage
            - mountPath: /app/collector/hotdir
              name: collector-hotdir
            - mountPath: /app/collector/outputs
              name: collector-outputs
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0
      containers:
        - image: mintplexlabs/anythingllm:master
          name: anything-llm
          ports:
            - containerPort: 3001
              hostPort: 3001
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app/server/storage
              name: server-storage
            - mountPath: /app/collector/hotdir
              name: collector-hotdir
            - mountPath: /app/collector/outputs
              name: collector-outputs
          lifecycle:
            postStart:
              exec:
                command:
                - "sh"
                - "-c"
                - >
                  if [ ! -f /app/server/storage/.env ]; then
                    touch /app/server/storage/.env;
                  fi;
                  ln -sf /app/server/storage/.env /app/server/.env
      restartPolicy: Always
      volumes:
        - name: server-storage
          persistentVolumeClaim:
            claimName: server-storage
        - name: collector-hotdir
          persistentVolumeClaim:
            claimName: collector-hotdir
        - name: collector-outputs
          persistentVolumeClaim:
            claimName: collector-outputs
status: {}


