apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-env
data:
  .env: |
    ALLOW_EMAIL_LOGIN: "true"
    ALLOW_REGISTRATION: "true"
    ALLOW_SOCIAL_LOGIN: "false"
    ALLOW_SOCIAL_REGISTRATION: "false"
    ANTHROPIC_API_KEY: ""
    ANTHROPIC_MODELS: claude-1,claude-instant-1,claude-2
    APP_TITLE: ChatGPT
    AZURE_AI_SEARCH_API_KEY: ""
    AZURE_AI_SEARCH_API_VERSION: ""
    AZURE_AI_SEARCH_INDEX_NAME: ""
    AZURE_AI_SEARCH_SEARCH_OPTION_QUERY_TYPE: ""
    AZURE_AI_SEARCH_SEARCH_OPTION_SELECT: ""
    AZURE_AI_SEARCH_SEARCH_OPTION_TOP: ""
    AZURE_AI_SEARCH_SERVICE_ENDPOINT: ""
    AZURE_API_KEY:
    AZURE_OPENAI_API_INSTANCE_NAME: chatgpt-test-ai
    AZURE_OPENAI_API_VERSION: 2023-09-01-preview
    AZURE_OPENAI_DEFAULT_MODEL: gpt-35-turbo
    AZURE_OPENAI_MODELS: gpt-35-turbo,gpt-4
    AZURE_USE_MODEL_AS_DEPLOYMENT_NAME: "TRUE"
    BAN_DURATION: 1000 * 60 * 60 * 2
    BAN_INTERVAL: "20"
    BAN_VIOLATIONS: "true"
    BINGAI_TOKEN: ""
    CHATGPT_MODELS: text-davinci-002-render-sha
    CHATGPT_TOKEN: ""
    CHECK_BALANCE: "false"
    CONCURRENT_MESSAGE_MAX: "2"
    CONCURRENT_VIOLATION_SCORE: "1"
    CREDS_IV: e2341419ec3dd3d19b13a1a87fafcbfb
    CREDS_KEY: f34be427ebb29de8d88c107a71546019685ed8b241d8f2ed00c3df97ad2566f0
    DEBUG_OPENAI: "true"
    DEBUG_PLUGINS: "true"
    DISCORD_CALLBACK_URL: /oauth/discord/callback
    DISCORD_CLIENT_ID: ""
    DISCORD_CLIENT_SECRET: ""
    DOMAIN_CLIENT: http://localhost:3080
    DOMAIN_SERVER: http://localhost:3080
    EMAIL_ALLOW_SELFSIGNED: ""
    EMAIL_ENCRYPTION: ""
    EMAIL_ENCRYPTION_HOSTNAME: ""
    EMAIL_FROM: noreply@librechat.ai
    EMAIL_FROM_NAME: ""
    EMAIL_HOST: ""
    EMAIL_PASSWORD: ""
    EMAIL_PORT: "25"
    EMAIL_SERVICE: ""
    EMAIL_USERNAME: ""
    ENDPOINTS: azureOpenAI
    FACEBOOK_CALLBACK_URL: /oauth/facebook/callback
    FACEBOOK_CLIENT_ID: ""
    FACEBOOK_CLIENT_SECRET: ""
    GITHUB_CALLBACK_URL: /oauth/github/callback
    GITHUB_CLIENT_ID: ""
    GITHUB_CLIENT_SECRET: ""
    GOOGLE_API_KEY: ""
    GOOGLE_CALLBACK_URL: /oauth/google/callback
    GOOGLE_CLIENT_ID: ""
    GOOGLE_CLIENT_SECRET: ""
    GOOGLE_CSE_ID: ""
    GOOGLE_KEY: ""
    HOST: localhost
    JWT_REFRESH_SECRET: eaa5191f2914e30b9387fd84e254e4ba6fc51b4654968a9b0803b456a54b8418
    JWT_SECRET: 16f8c0ef4a5d391b26034086c628469d3f9f497f08163ab9b40137092f2909ef
    LIMIT_CONCURRENT_MESSAGES: "true"
    LIMIT_MESSAGE_IP: "true"
    LIMIT_MESSAGE_USER: "false"
    LOGIN_MAX: "7"
    LOGIN_VIOLATION_SCORE: "1"
    LOGIN_WINDOW: "5"
    MEILI_HOST: http://millisearch:7700
    MEILI_HTTP_ADDR: millisearch:7700
    MEILI_MASTER_KEY: DrhYf7zENyR6AlUCKmnz0eYASOQdl6zxH7s7MKFSfFCt
    MEILI_NO_ANALYTICS: "true"
    MESSAGE_IP_MAX: "40"
    MESSAGE_IP_WINDOW: "1"
    MESSAGE_USER_MAX: "40"
    MESSAGE_USER_WINDOW: "1"
    MESSAGE_VIOLATION_SCORE: "1"
    MONGO_URI: mongodb://mongodb:27017/LibreChat
    NON_BROWSER_VIOLATION_SCORE: "20"
    OPENAI_API_KEY: ""
    OPENID_BUTTON_LABEL: ""
    OPENID_CALLBACK_URL: /oauth/openid/callback
    OPENID_CLIENT_ID: ""
    OPENID_CLIENT_SECRET: ""
    OPENID_IMAGE_URL: ""
    OPENID_ISSUER: ""
    OPENID_SCOPE: openid profile email
    OPENID_SESSION_SECRET: ""
    PLUGINS_USE_AZURE: "true"
    PORT: "3080"
    PROXY: ""
    REFRESH_TOKEN_EXPIRY: (1000 * 60 * 60 * 24) * 7
    REGISTER_MAX: "5"
    REGISTER_WINDOW: "60"
    REGISTRATION_VIOLATION_SCORE: "1"
    SD_WEBUI_URL: http://host.docker.internal:7860
    SEARCH: "true"
    SERPAPI_API_KEY: ""
    SESSION_EXPIRY: 1000 * 60 * 15
    WOLFRAM_APP_ID: ""
    ZAPIER_NLA_API_KEY: ""

