apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: meilisearch
  name: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: meilisearch
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/librechat-default: "true"
        io.kompose.service: meilisearch
    spec:
      containers:
        - env:
            - name: MEILI_HOST
              value: http://0.0.0.0:7700
            - name: MEILI_HTTP_ADDR
              value: 0.0.0.0:7700
            - name: MEILI_MASTER_KEY
              value: DrhYf7zENyR6AlUCKmnz0eYASOQdl6zxH7s7MKFSfFCt
            - name: MEILI_NO_ANALYTICS
              value: "true"
          image: getmeili/meilisearch:v1.5
          name: chat-meilisearch
          resources: {}
          volumeMounts:
            - mountPath: /meili_data
              name: meilisearch-claim0
      restartPolicy: Always
      volumes:
        - name: meilisearch-claim0
          persistentVolumeClaim:
            claimName: meilisearch-claim0
status: {}
