apiVersion: v1
kind: Service
metadata:
  name: millisearch
spec:
  ports:
    - name: "port"
      port: 7700
      targetPort: 7700
  selector:
    io.kompose.service: millisearch
status:
  loadBalancer: {}
